// functions/src/features/users/schemas.ts
export { z } from "@hdb/contracts";

export {
  // runtime
  RoleTagCanonical,
  TopRoleCanonical,
  TopRoleLadder,
  RoleInput,
  RolesArray,
  CreateUserBody,
  InviteUserBody,
  SetRoleBody,
  SetActiveBody,
  UpdateUserProfileBody,
  ResendInviteBody,
  RevokeSessionsBody,
  ListUsersBody,
  OrgManagerTeam,
  OrgManagerOrg,
  OrgManagerListOrgsBody,
  OrgManagerUpsertOrgBody,
  OrgManagerPatchTeamsBody,
  UserMetrics,
  UserTaskMetrics,
  UserPaymentMetrics,
  UserDashboardPrefs,
  UserGameRecord,
  UserGameMeta,
  UserGameHighScores,
  UserExtras,
  UpdateMeBody,
} from "@hdb/contracts";

export type {
  // literals / core leaf types
  TRoleTag,
  TRoles,
  TTopRole,
  TTopRoleLadder,
  TRole,
  TUserMetrics,
  TUserTaskMetrics,
  TUserPaymentMetrics,
  TUserDashboardPrefs,
  TUserGameRecord,
  TUserGameMeta,
  TUserGameHighScores,
  TUserExtras,
  TUserListStatus,
  OrgManagerTeamT,
  OrgManagerOrgT,
  OrgManagerListOrgsBodyT,
  OrgManagerUpsertOrgBodyT,
  OrgManagerPatchTeamsBodyT,
  UserComposite,

  // body outputs (post-parse)
  CreateUserBodyT,
  InviteUserBodyT,
  SetRoleBodyT,
  SetActiveBodyT,
  UpdateUserProfileBodyT,
  ResendInviteBodyT,
  RevokeSessionsBodyT,
  ListUsersBodyT,
  UpdateMeBodyT,

  // inputs
  CreateUserBodyIn,
  InviteUserBodyIn,
  SetRoleBodyIn,
  SetActiveBodyIn,
  UpdateUserProfileBodyIn,
  ResendInviteBodyIn,
  RevokeSessionsBodyIn,
  ListUsersBodyIn,
  OrgManagerListOrgsBodyIn,
  OrgManagerUpsertOrgBodyIn,
  OrgManagerPatchTeamsBodyIn,
  UpdateMeBodyIn,
} from "@hdb/contracts";
