"use client";

import React from "react";
import type { OrgConfigDoc } from "@client/orgs";
import dynamic from "next/dynamic";

const RichTextEditor = dynamic(
  () => import("@entities/help/RichTextEditor").then((m) => m.RichTextEditor),
  { ssr: false, loading: () => <div className="p-4 text-xs text-slate-400">Loading editor…</div> }
);

const KIND_LABELS: Record<string, string> = {
  display: "Display",
  system: "System",
  email_template: "Email Template",
};

type DigestBoxKey = "rentalAssistance" | "customer" | "budget";

type DigestStructure = {
  version: number;
  digestType: string;
  editorNotesHtml: string;
  subject: { template: string; description: string };
  intro: { enabled: boolean; html: string; description: string };
  boxes: Record<
    DigestBoxKey,
    {
      enabled: boolean;
      title: string;
      description: string;
      fields: Array<{ key: string; label: string; enabled: boolean; description: string }>;
    }
  >;
  footer: { enabled: boolean; html: string; description: string };
};

const DIGEST_TEMPLATE_TYPE_BY_DOC_ID: Record<string, string> = {
  CustomerEmailTemplate: "caseload",
  CaseManagersEmailTemplate: "caseManagers",
  BudgetEmailTemplate: "budget",
  EnrollmentsEmailTemplate: "enrollments",
  RentalAssistanceEmailTemplate: "rentalAssistance",
};

const DIGEST_BOX_LABELS: Record<DigestBoxKey, string> = {
  rentalAssistance: "Rental assistance box",
  customer: "Customer box",
  budget: "Budget box",
};

const DEFAULT_DIGEST_NOTES = [
  "<h2>Digest structure build notes</h2>",
  "<p>This scaffold is saved with the org config doc so the next implementation pass has durable product notes beside the editable structure.</p>",
  "<ul>",
  "<li>Backend renderers should read <code>value.digestStructure</code> and fall back to current hard-coded digest sections when fields are missing.</li>",
  "<li>Keep the real email preview sourced from <code>inboxDigestHtmlPreview</code>; avoid a second incompatible frontend renderer.</li>",
  "<li>Fields should become selectable from real digest data keys after the backend exposes a digest schema endpoint.</li>",
  "</ul>",
].join("");

function defaultDigestStructure(doc: OrgConfigDoc): DigestStructure {
  const digestType = DIGEST_TEMPLATE_TYPE_BY_DOC_ID[doc.id] || doc.id;
  return {
    version: 1,
    digestType,
    editorNotesHtml: DEFAULT_DIGEST_NOTES,
    subject: {
      template: String(doc.subject || `${doc.label} - {{monthLabel}}`),
      description: "Subject line used by scheduled and manual digest sends.",
    },
    intro: {
      enabled: true,
      html: String(doc.bodyHtml || "<p>Monthly digest summary.</p>"),
      description: "Optional copy shown above the digest boxes.",
    },
    boxes: {
      rentalAssistance: {
        enabled: digestType === "rentalAssistance",
        title: "Rental Assistance",
        description: "Grant rental assistance metrics, household activity, payments, and upcoming pressure points.",
        fields: [
          { key: "totalAssistance", label: "Total assistance", enabled: true, description: "Total rental assistance for the digest period." },
          { key: "householdsServed", label: "Households served", enabled: true, description: "Count of unique households assisted." },
        ],
      },
      customer: {
        enabled: true,
        title: "Customers",
        description: "Customer-level activity, enrollment status, and compliance follow-up signals.",
        fields: [
          { key: "activeCustomers", label: "Active customers", enabled: true, description: "Customers active in the digest scope." },
          { key: "newCustomers", label: "New customers", enabled: true, description: "Customers created during the digest period." },
        ],
      },
      budget: {
        enabled: digestType === "budget" || digestType === "rentalAssistance",
        title: "Budget",
        description: "Budget total, spent, projected, remaining funds, and pinned grant rollups.",
        fields: [
          { key: "budgetTotal", label: "Budget total", enabled: true, description: "Total budget in digest scope." },
          { key: "remaining", label: "Remaining", enabled: true, description: "Remaining funds after spend and projections." },
        ],
      },
    },
    footer: {
      enabled: true,
      html: "<p>Generated by Households DB.</p>",
      description: "Footer copy appended to the email.",
    },
  };
}

function normalizeDigestStructure(doc: OrgConfigDoc): DigestStructure {
  const base = defaultDigestStructure(doc);
  const rawValue = doc.value && typeof doc.value === "object" ? doc.value : {};
  const saved =
    rawValue.digestStructure && typeof rawValue.digestStructure === "object"
      ? (rawValue.digestStructure as Partial<DigestStructure>)
      : {};
  return {
    ...base,
    ...saved,
    subject: { ...base.subject, ...(saved.subject || {}) },
    intro: { ...base.intro, ...(saved.intro || {}) },
    boxes: {
      rentalAssistance: { ...base.boxes.rentalAssistance, ...(saved.boxes?.rentalAssistance || {}) },
      customer: { ...base.boxes.customer, ...(saved.boxes?.customer || {}) },
      budget: { ...base.boxes.budget, ...(saved.boxes?.budget || {}) },
    },
    footer: { ...base.footer, ...(saved.footer || {}) },
  };
}

export function JsonValueEditor({
  doc,
  onSave,
  saving,
}: {
  doc: OrgConfigDoc;
  onSave: (patch: Record<string, unknown>) => void;
  saving: boolean;
}) {
  const initialText = React.useMemo(() => JSON.stringify(doc.value ?? {}, null, 2), [doc.value]);
  const [text, setText] = React.useState(initialText);
  const [parseError, setParseError] = React.useState<string | null>(null);

  React.useEffect(() => {
    setText(initialText);
    setParseError(null);
  }, [initialText]);

  const dirty = text !== initialText;

  const handleSave = () => {
    try {
      const parsed = JSON.parse(text);
      setParseError(null);
      onSave({ value: parsed });
    } catch (e: unknown) {
      setParseError(e instanceof Error ? e.message : "Invalid JSON");
    }
  };

  return (
    <div className="space-y-2">
      <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400">Value (JSON)</label>
      <textarea
        className={[
          "w-full rounded-lg border px-3 py-2 font-mono text-sm focus:outline-none focus:ring-2 focus:ring-slate-300 dark:bg-slate-950 dark:text-slate-100",
          parseError ? "border-red-400 bg-red-50" : "border-slate-300 bg-white dark:border-slate-700",
        ].join(" ")}
        rows={16}
        value={text}
        onChange={(e) => {
          setText(e.currentTarget.value);
          setParseError(null);
        }}
      />
      {parseError ? <div className="text-xs text-red-600">{parseError}</div> : null}
      <button type="button" disabled={!dirty || saving} className="btn btn-sm btn-primary" onClick={handleSave}>
        {saving ? "Saving..." : "Save Config"}
      </button>
    </div>
  );
}

export function DigestScaffoldEditor({
  doc,
  onSave,
  saving,
}: {
  doc: OrgConfigDoc;
  onSave: (patch: Record<string, unknown>) => void;
  saving: boolean;
}) {
  const normalized = React.useMemo(() => normalizeDigestStructure(doc), [doc]);
  const [subject, setSubject] = React.useState(doc.subject || "");
  const [bodyText, setBodyText] = React.useState(doc.bodyText || "");
  const [bodyHtml, setBodyHtml] = React.useState(doc.bodyHtml || "");
  const [structure, setStructure] = React.useState<DigestStructure>(normalized);

  React.useEffect(() => {
    setSubject(doc.subject || "");
    setBodyText(doc.bodyText || "");
    setBodyHtml(doc.bodyHtml || "");
    setStructure(normalized);
  }, [doc, normalized]);

  const dirty =
    subject !== (doc.subject || "") ||
    bodyText !== (doc.bodyText || "") ||
    bodyHtml !== (doc.bodyHtml || "") ||
    JSON.stringify(structure) !== JSON.stringify(normalized);

  const patchBox = (key: DigestBoxKey, patch: Partial<DigestStructure["boxes"][DigestBoxKey]>) => {
    setStructure((current) => ({
      ...current,
      boxes: {
        ...current.boxes,
        [key]: { ...current.boxes[key], ...patch },
      },
    }));
  };

  const save = () => {
    onSave({
      subject,
      bodyText,
      bodyHtml,
      value: {
        ...(doc.value || {}),
        digestStructure: {
          ...structure,
          subject: { ...structure.subject, template: subject },
          intro: { ...structure.intro, html: structure.intro.html || bodyHtml },
        },
      },
    });
  };

  return (
    <div className="space-y-4">
      <div className="rounded-lg border border-sky-200 bg-sky-50 px-3 py-2 text-sm text-sky-900 dark:border-sky-900 dark:bg-sky-950 dark:text-sky-100">
        Scaffold mode: this saves a structured digest object on the org config doc. Backend digest renderers still need a later pass to consume it.
      </div>

      <section className="grid gap-3 md:grid-cols-2">
        <label className="block">
          <span className="mb-1 block text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Digest type</span>
          <input
            className="input"
            value={structure.digestType}
            onChange={(event) => {
              const value = event.currentTarget.value;
              setStructure((current) => ({ ...current, digestType: value }));
            }}
          />
        </label>
        <label className="block">
          <span className="mb-1 block text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Subject template</span>
          <input
            className="input"
            value={subject}
            onChange={(event) => {
              const value = event.currentTarget.value;
              setSubject(value);
              setStructure((current) => ({ ...current, subject: { ...current.subject, template: value } }));
            }}
            placeholder="Digest subject line..."
          />
        </label>
      </section>

      <section className="space-y-2">
        <div>
          <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">Implementation notes</div>
          <div className="text-xs text-slate-500 dark:text-slate-400">Durable build notes, assumptions, and migration reminders saved with this template.</div>
        </div>
        <RichTextEditor value={structure.editorNotesHtml} onChange={(html) => setStructure((current) => ({ ...current, editorNotesHtml: html }))} />
      </section>

      <section className="space-y-2">
        <div className="flex items-center justify-between gap-3">
          <div>
            <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">Intro block</div>
            <div className="text-xs text-slate-500 dark:text-slate-400">{structure.intro.description}</div>
          </div>
          <label className="inline-flex items-center gap-2 text-xs font-semibold text-slate-600 dark:text-slate-300">
            <input
              type="checkbox"
              checked={structure.intro.enabled}
              onChange={(event) => {
                const checked = event.currentTarget.checked;
                setStructure((current) => ({ ...current, intro: { ...current.intro, enabled: checked } }));
              }}
            />
            Enabled
          </label>
        </div>
        <RichTextEditor
          value={structure.intro.html}
          onChange={(html) => {
            setBodyHtml(html);
            setStructure((current) => ({ ...current, intro: { ...current.intro, html } }));
          }}
        />
      </section>

      <section className="grid gap-3 lg:grid-cols-3">
        {(Object.keys(structure.boxes) as DigestBoxKey[]).map((key) => {
          const box = structure.boxes[key];
          return (
            <div key={key} className="rounded-lg border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-950">
              <label className="flex items-start justify-between gap-3">
                <span>
                  <span className="block text-sm font-semibold text-slate-900 dark:text-slate-100">{DIGEST_BOX_LABELS[key]}</span>
                  <span className="block text-xs text-slate-500 dark:text-slate-400">{box.description}</span>
                </span>
                <input type="checkbox" checked={box.enabled} onChange={(event) => patchBox(key, { enabled: event.currentTarget.checked })} />
              </label>
              <label className="mt-3 block">
                <span className="mb-1 block text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Title</span>
                <input className="input" value={box.title} onChange={(event) => patchBox(key, { title: event.currentTarget.value })} />
              </label>
              <label className="mt-3 block">
                <span className="mb-1 block text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Description</span>
                <textarea className="input min-h-20" value={box.description} onChange={(event) => patchBox(key, { description: event.currentTarget.value })} />
              </label>
              <div className="mt-3 space-y-1">
                <div className="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Field scaffold</div>
                {box.fields.map((field) => (
                  <label key={field.key} className="flex items-start gap-2 rounded border border-slate-100 bg-slate-50 px-2 py-1 dark:border-slate-800 dark:bg-slate-900">
                    <input
                      type="checkbox"
                      className="mt-1"
                      checked={field.enabled}
                      onChange={(event) => {
                        const fields = box.fields.map((item) => (item.key === field.key ? { ...item, enabled: event.currentTarget.checked } : item));
                        patchBox(key, { fields });
                      }}
                    />
                    <span>
                      <span className="block text-xs font-semibold text-slate-800 dark:text-slate-100">{field.label}</span>
                      <span className="block text-[11px] text-slate-500 dark:text-slate-400">{field.description}</span>
                    </span>
                  </label>
                ))}
              </div>
            </div>
          );
        })}
      </section>

      <section className="space-y-2">
        <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400">Plain text fallback</label>
        <textarea className="input min-h-28 font-mono" value={bodyText} onChange={(event) => setBodyText(event.currentTarget.value)} placeholder="Plain text body..." />
      </section>

      <details className="rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950">
        <summary className="cursor-pointer text-sm font-semibold text-slate-700 dark:text-slate-200">Advanced raw HTML / object preview</summary>
        <label className="mt-3 block">
          <span className="mb-1 block text-xs font-semibold text-slate-500 dark:text-slate-400">Body HTML</span>
          <textarea className="input min-h-52 font-mono" value={bodyHtml} onChange={(event) => setBodyHtml(event.currentTarget.value)} placeholder="<html>..." />
        </label>
        <pre className="mt-3 max-h-72 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">
          {JSON.stringify({ digestStructure: structure }, null, 2)}
        </pre>
      </details>

      <button type="button" disabled={!dirty || saving} className="btn btn-sm btn-primary" onClick={save}>
        {saving ? "Saving..." : "Save Digest Scaffold"}
      </button>
    </div>
  );
}

export function ConfigDocEditorCard({
  doc,
  onSave,
  saving,
}: {
  doc: OrgConfigDoc;
  onSave: (patch: Record<string, unknown>) => void;
  saving: boolean;
}) {
  return (
    <div className="rounded-lg border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900">
      <div className="border-b border-slate-200 bg-slate-50 px-4 py-3 dark:border-slate-700 dark:bg-slate-950">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">{doc.label}</div>
            <div className="font-mono text-xs text-slate-500 dark:text-slate-400">{doc.id}</div>
          </div>
          <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400">
            <span>{KIND_LABELS[doc.kind] ?? doc.kind}</span>
            {doc.updatedAt ? <span>Updated {new Date(doc.updatedAt).toLocaleDateString()}</span> : null}
          </div>
        </div>
      </div>
      <div className="p-4">
        {doc.kind === "email_template" ? (
          <DigestScaffoldEditor doc={doc} onSave={onSave} saving={saving} />
        ) : (
          <JsonValueEditor doc={doc} onSave={onSave} saving={saving} />
        )}
      </div>
    </div>
  );
}

