import type { TEnrollment, TGrant, TPayment } from "@types";
import type { PaymentsProjectionsAdjustInput } from "@hooks/usePayments";

export type PaymentEditorTypeKey = "monthly-rent" | "monthly-utility" | "deposit" | "prorated" | "service" | "arrears";
export type PaymentEditorLedgerStatus = "projected" | "invoice-submitted";
export type PaymentEditorComplianceStatus = "hmis-only" | "caseworthy-only" | "data-entry-complete";

export type PaymentEditorLineItemOption = {
  id: string;
  label: string;
};

export type PaymentEditorGrantInfo = {
  id: string;
  name: string;
  code: string;
  lineItems: PaymentEditorLineItemOption[];
  invoice?: {
    invoiceCode?: string;
    grantCode?: string;
    funder?: string;
    contractNumber?: string;
    frequency?: string;
    dueDayOfMonth?: string;
    paymentTerms?: string;
    submissionPortal?: string;
    notes?: string;
  };
};

export type PaymentEditorEnrollmentOption = {
  id: string;
  label: string;
  customerId: string;
  customerName: string;
  grantId: string;
  grantName: string;
  statusLabel: "open" | "closed";
  lineItems: PaymentEditorLineItemOption[];
  rawEnrollment: TEnrollment | Record<string, unknown>;
};

export type PaymentEditorRow = {
  id: string;
  enrollmentId: string;
  customerId: string;
  customerName: string;
  grantId: string;
  grantName: string;
  sourcePaymentId: string;
  sourceIndex: number;
  dueDate: string;
  typeKey: PaymentEditorTypeKey | "";
  lineItemId: string;
  lineItemName: string;
  amount: string;
  vendor: string;
  notes: string;
  rentCertDue: boolean;
  rentCertDueAutoGenerated?: boolean;
  complianceStatus: PaymentEditorComplianceStatus;
  paidStatus: PaymentEditorLedgerStatus;
  originalPaidStatus: PaymentEditorLedgerStatus;
  paid: boolean;
  source: "schedule" | "adjustment" | "new";
  lockedReason?: string;
};

export type PaymentEditorBaseline = {
  fingerprints: Map<string, string>;
  rows: Map<string, PaymentEditorRow>;
};

export type PaymentEditorSavePlan = {
  validationErrors: string[];
  compliancePatches: Array<{
    enrollmentId: string;
    paymentId: string;
    patch: { hmisComplete: boolean; caseworthyComplete: boolean; status?: string | null };
  }>;
  spendPosts: Array<{ enrollmentId: string; paymentId: string; note?: string; vendor?: string }>;
  rentCertPatches: Array<{ enrollmentId: string; paymentId: string; status: "notDue" | "due" }>;
  projectionAdjustments: Array<PaymentsProjectionsAdjustInput>;
  paidAdjustments: Array<PaymentsProjectionsAdjustInput>;
  paidDeletes: Array<PaymentsProjectionsAdjustInput>;
  changedRowIds: Set<string>;
};

const TYPE_TO_PAYMENT_TYPE: Record<PaymentEditorTypeKey, TPayment["type"]> = {
  "monthly-rent": "monthly",
  "monthly-utility": "monthly",
  deposit: "deposit",
  prorated: "prorated",
  service: "service",
  arrears: "arrears",
};

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" ? (value as Record<string, unknown>) : {};
}

function normalizeText(value: unknown): string {
  return String(value ?? "").trim();
}

function normalizeAmount(value: unknown): string {
  const raw = normalizeText(value);
  if (!raw) return "";
  const n = Number(raw);
  return Number.isFinite(n) ? String(Math.round(n * 100)) : raw;
}

function amountNumber(value: unknown): number {
  const n = Number(value);
  return Number.isFinite(n) ? Number(n.toFixed(2)) : 0;
}

function iso10(value: unknown): string {
  const raw = normalizeText(value);
  if (!raw) return "";
  if (/^\d{4}-\d{2}-\d{2}/.test(raw)) return raw.slice(0, 10);
  const parsed = new Date(raw);
  return Number.isNaN(parsed.getTime()) ? "" : parsed.toISOString().slice(0, 10);
}

function notesText(value: unknown): string {
  if (Array.isArray(value)) return value.map((item) => normalizeText(item)).filter(Boolean).join("; ");
  return normalizeText(value);
}

function displayNotes(value: unknown): string {
  if (!Array.isArray(value)) return normalizeText(value);
  return value
    .map((item) => normalizeText(item))
    .filter((item) => item && !item.toLowerCase().startsWith("sub:") && !["rent", "utility"].includes(item.toLowerCase()))
    .join("; ");
}

function paymentNotes(typeKey: PaymentEditorTypeKey | "", notes: string): string | string[] | undefined {
  const note = normalizeText(notes);
  if (typeKey === "monthly-rent") return note ? ["sub:rent", note] : ["sub:rent"];
  if (typeKey === "monthly-utility") return note ? ["sub:utility", note] : ["sub:utility"];
  return note || undefined;
}

function paymentTypeKey(payment: Record<string, unknown>): PaymentEditorTypeKey | "" {
  const type = normalizeText(payment.type || "monthly").toLowerCase();
  if (type === "deposit") return "deposit";
  if (type === "prorated") return "prorated";
  if (type === "service") return "service";
  if (type === "arrears") return "arrears";
  const note = notesText(payment.note).toLowerCase();
  if (note.includes("utility")) return "monthly-utility";
  return "monthly-rent";
}

function complianceStatus(payment: Record<string, unknown>): PaymentEditorComplianceStatus {
  const comp = asRecord(payment.compliance);
  const hmis = comp.hmisComplete === true;
  const caseworthy = comp.caseworthyComplete === true;
  if (hmis && caseworthy) return "data-entry-complete";
  if (caseworthy) return "caseworthy-only";
  return "hmis-only";
}

export function compliancePatchFromStatus(status: PaymentEditorComplianceStatus) {
  return {
    hmisComplete: status === "hmis-only" || status === "data-entry-complete",
    caseworthyComplete: status === "caseworthy-only" || status === "data-entry-complete",
    status: status === "data-entry-complete" ? "data-entry-complete" : null,
  };
}

function lineItemsFromGrant(grant: Record<string, unknown>): PaymentEditorLineItemOption[] {
  const budget = asRecord(grant.budget);
  const raw = Array.isArray(budget.lineItems) ? budget.lineItems : [];
  return raw
    .map((item) => {
      const row = asRecord(item);
      const id = normalizeText(row.id);
      if (!id) return null;
      return { id, label: normalizeText(row.label || row.name || row.title || row.code) || id };
    })
    .filter((item): item is PaymentEditorLineItemOption => !!item);
}

export function inferPaymentEditorLineItemId(typeKey: PaymentEditorTypeKey | "", options: PaymentEditorLineItemOption[]) {
  if (!options.length) return "";
  const terms: Record<PaymentEditorTypeKey, string[]> = {
    "monthly-rent": ["rent", "rental"],
    "monthly-utility": ["utility", "utilities"],
    deposit: ["deposit", "security"],
    prorated: ["prorated", "prorate"],
    service: ["service", "support"],
    arrears: ["arrears", "past due"],
  };
  const wanted = typeKey ? terms[typeKey] : [];
  const found = options.find((item) => {
    const blob = `${item.id} ${item.label}`.toLowerCase();
    return wanted.some((term) => blob.includes(term));
  });
  return found?.id || options[0]?.id || "";
}

export function buildPaymentEditorGrantInfo(grants: Array<TGrant | Record<string, unknown>>): Map<string, PaymentEditorGrantInfo> {
  const out = new Map<string, PaymentEditorGrantInfo>();
  for (const rawGrant of grants) {
    const grant = asRecord(rawGrant);
    const id = normalizeText(grant.id);
    if (!id) continue;
    const inv = asRecord(grant.invoicing);
    out.set(id, {
      id,
      name: normalizeText(grant.name || grant.title || grant.label) || id,
      code: normalizeText(grant.code || inv.grantCode || inv.invoiceCode),
      lineItems: lineItemsFromGrant(grant),
      invoice: Object.keys(inv).length
        ? {
            invoiceCode: normalizeText(inv.invoiceCode),
            grantCode: normalizeText(inv.grantCode),
            funder: normalizeText(inv.funder),
            contractNumber: normalizeText(inv.contractNumber),
            frequency: normalizeText(inv.frequency),
            dueDayOfMonth: inv.dueDayOfMonth == null ? "" : normalizeText(inv.dueDayOfMonth),
            paymentTerms: normalizeText(inv.paymentTerms),
            submissionPortal: normalizeText(inv.submissionPortal),
            notes: normalizeText(inv.notes),
          }
        : undefined,
    });
  }
  return out;
}

export function buildPaymentEditorEnrollmentOptions(
  enrollments: Array<TEnrollment | Record<string, unknown>>,
  grantsById: Map<string, PaymentEditorGrantInfo>,
): PaymentEditorEnrollmentOption[] {
  return enrollments.map((rawEnrollment) => {
    const enrollment = asRecord(rawEnrollment);
    const id = normalizeText(enrollment.id);
    const grantId = normalizeText(enrollment.grantId);
    const grant = grantsById.get(grantId);
    const status = normalizeText(enrollment.status).toLowerCase();
    return {
      id,
      label: normalizeText(enrollment.name || enrollment.programName || enrollment.grantName) || id || "Enrollment",
      customerId: normalizeText(enrollment.customerId || enrollment.clientId),
      customerName: normalizeText(enrollment.customerName || enrollment.clientName),
      grantId,
      grantName: grant?.name || normalizeText(enrollment.grantName) || grantId,
      statusLabel: status === "closed" || status === "deleted" ? "closed" : "open",
      lineItems: grant?.lineItems || [],
      rawEnrollment,
    };
  });
}

export function buildPaymentEditorRows(args: {
  enrollments: Array<TEnrollment | Record<string, unknown>>;
  grantsById: Map<string, PaymentEditorGrantInfo>;
}): PaymentEditorRow[] {
  const rows: PaymentEditorRow[] = [];
  const enrollmentOptions = buildPaymentEditorEnrollmentOptions(args.enrollments, args.grantsById);
  const enrollmentById = new Map(enrollmentOptions.map((item) => [item.id, item]));

  for (const rawEnrollment of args.enrollments) {
    const enrollment = asRecord(rawEnrollment);
    const enrollmentId = normalizeText(enrollment.id);
    const option = enrollmentById.get(enrollmentId);
    const payments = Array.isArray(enrollment.payments) ? enrollment.payments : [];
    payments.forEach((rawPayment, index) => {
      const payment = asRecord(rawPayment);
      const sourcePaymentId = normalizeText(payment.id) || `idx_${index}`;
      const typeKey = paymentTypeKey(payment);
      const lineItemId = normalizeText(payment.lineItemId);
      const lineItem = option?.lineItems.find((item) => item.id === lineItemId);
      const paid = payment.paid === true;
      rows.push({
        id: `${enrollmentId}:${sourcePaymentId}`,
        enrollmentId,
        customerId: option?.customerId || "",
        customerName: option?.customerName || "",
        grantId: option?.grantId || "",
        grantName: option?.grantName || "",
        sourcePaymentId,
        sourceIndex: index,
        dueDate: iso10(payment.dueDate || payment.date),
        typeKey,
        lineItemId,
        lineItemName: lineItem?.label || lineItemId,
        amount: normalizeText(payment.amount),
        vendor: normalizeText(payment.vendor),
        notes: displayNotes(payment.note || payment.comment),
        rentCertDue: Boolean(asRecord(payment.rentCert).dueDate || payment.rentCertDue || asRecord(payment.meta).rentCertDue),
        complianceStatus: complianceStatus(payment),
        paidStatus: paid ? "invoice-submitted" : "projected",
        originalPaidStatus: paid ? "invoice-submitted" : "projected",
        paid,
        source: "schedule",
        lockedReason: paid ? "Paid row schedule edits use adjustment-safe save handling." : undefined,
      });
    });
  }

  return rows;
}

export function makeBlankPaymentEditorRow(enrollment: PaymentEditorEnrollmentOption): PaymentEditorRow {
  const typeKey: PaymentEditorTypeKey = "monthly-rent";
  const lineItemId = inferPaymentEditorLineItemId(typeKey, enrollment.lineItems);
  const lineItem = enrollment.lineItems.find((item) => item.id === lineItemId);
  return {
    id: `new_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`,
    enrollmentId: enrollment.id,
    customerId: enrollment.customerId,
    customerName: enrollment.customerName,
    grantId: enrollment.grantId,
    grantName: enrollment.grantName,
    sourcePaymentId: "",
    sourceIndex: -1,
    dueDate: "",
    typeKey,
    lineItemId,
    lineItemName: lineItem?.label || lineItemId,
    amount: "",
    vendor: "",
    notes: "",
    rentCertDue: false,
    complianceStatus: "hmis-only",
    paidStatus: "projected",
    originalPaidStatus: "projected",
    paid: false,
    source: "new",
  };
}

export function normalizePaymentEditorRow(row: PaymentEditorRow): string {
  return JSON.stringify({
    enrollmentId: normalizeText(row.enrollmentId),
    sourcePaymentId: normalizeText(row.sourcePaymentId),
    dueDate: normalizeText(row.dueDate),
    typeKey: normalizeText(row.typeKey),
    lineItemId: normalizeText(row.lineItemId),
    amountCents: normalizeAmount(row.amount),
    vendor: normalizeText(row.vendor),
    notes: normalizeText(row.notes),
    rentCertDue: Boolean(row.rentCertDue),
    complianceStatus: row.complianceStatus,
    paidStatus: row.paidStatus,
    source: row.source,
  });
}

export function createPaymentEditorBaseline(rows: PaymentEditorRow[]): PaymentEditorBaseline {
  return {
    fingerprints: new Map(rows.map((row) => [row.id, normalizePaymentEditorRow(row)])),
    rows: new Map(rows.map((row) => [row.id, row])),
  };
}

export function getChangedPaymentEditorRowIds(
  baseline: PaymentEditorBaseline,
  rows: PaymentEditorRow[],
): Set<string> {
  const changed = new Set<string>();
  const currentIds = new Set<string>();

  for (const row of rows) {
    currentIds.add(row.id);
    const baselineValue = baseline.fingerprints.get(row.id);
    if (baselineValue == null || baselineValue !== normalizePaymentEditorRow(row)) {
      changed.add(row.id);
    }
  }

  for (const id of baseline.fingerprints.keys()) {
    if (!currentIds.has(id)) changed.add(id);
  }

  return changed;
}

function isScheduleChanged(before: PaymentEditorRow, after: PaymentEditorRow): boolean {
  return before.dueDate !== after.dueDate ||
    before.typeKey !== after.typeKey ||
    before.lineItemId !== after.lineItemId ||
    normalizeAmount(before.amount) !== normalizeAmount(after.amount) ||
    before.vendor !== after.vendor ||
    before.notes !== after.notes;
}

function isComplianceChanged(before: PaymentEditorRow, after: PaymentEditorRow): boolean {
  return before.complianceStatus !== after.complianceStatus;
}

function toProjectionAddition(row: PaymentEditorRow) {
  if (!row.typeKey) return null;
  return {
    amount: amountNumber(row.amount),
    dueDate: row.dueDate,
    lineItemId: row.lineItemId,
    type: TYPE_TO_PAYMENT_TYPE[row.typeKey],
    note: paymentNotes(row.typeKey, row.notes),
    vendor: row.vendor || undefined,
  };
}

function toProjectionEdit(row: PaymentEditorRow) {
  if (!row.typeKey || !row.sourcePaymentId) return null;
  return {
    paymentId: row.sourcePaymentId,
    amount: amountNumber(row.amount),
    dueDate: row.dueDate,
    lineItemId: row.lineItemId,
    type: TYPE_TO_PAYMENT_TYPE[row.typeKey],
    note: paymentNotes(row.typeKey, row.notes),
    vendor: row.vendor || undefined,
  };
}

export function buildPaymentEditorSavePlan(
  baseline: PaymentEditorBaseline,
  rows: PaymentEditorRow[],
): PaymentEditorSavePlan {
  const changedRowIds = getChangedPaymentEditorRowIds(baseline, rows);
  const validationErrors: string[] = [];
  const compliancePatches: PaymentEditorSavePlan["compliancePatches"] = [];
  const spendPosts: PaymentEditorSavePlan["spendPosts"] = [];
  const rentCertPatches: PaymentEditorSavePlan["rentCertPatches"] = [];
  const projectionByEnrollment = new Map<string, NonNullable<PaymentsProjectionsAdjustInput["projectionAdjustment"]>>();
  const paidAdjustments: PaymentEditorSavePlan["paidAdjustments"] = [];
  const paidDeletes: PaymentEditorSavePlan["paidDeletes"] = [];
  const currentById = new Map(rows.map((row) => [row.id, row]));

  const ensureProjection = (enrollmentId: string) => {
    const existing = projectionByEnrollment.get(enrollmentId);
    if (existing) return existing;
    const next: NonNullable<PaymentsProjectionsAdjustInput["projectionAdjustment"]> = {
      edits: [],
      additions: [],
      deleteIds: [],
      replaceUnpaid: true,
    };
    projectionByEnrollment.set(enrollmentId, next);
    return next;
  };

  for (const row of rows) {
    if (!changedRowIds.has(row.id)) continue;
    const before = baseline.rows.get(row.id);
    if (!row.enrollmentId) validationErrors.push(`${row.id}: enrollment is required.`);
    if (!row.dueDate) validationErrors.push(`${row.id}: due date is required.`);
    if (!row.typeKey) validationErrors.push(`${row.id}: type is required.`);
    if (!row.lineItemId) validationErrors.push(`${row.id}: line item is required.`);
    if (row.amount === "" || !Number.isFinite(Number(row.amount)) || amountNumber(row.amount) < 0) {
      validationErrors.push(`${row.id}: amount must be 0 or greater.`);
    }

    if (!before) {
      const add = toProjectionAddition(row);
      if (add) ensureProjection(row.enrollmentId).additions!.push(add);
      continue;
    }

    if (isComplianceChanged(before, row) && row.sourcePaymentId) {
      compliancePatches.push({
        enrollmentId: row.enrollmentId,
        paymentId: row.sourcePaymentId,
        patch: compliancePatchFromStatus(row.complianceStatus),
      });
    }

    if (before.rentCertDue !== row.rentCertDue && row.sourcePaymentId) {
      rentCertPatches.push({
        enrollmentId: row.enrollmentId,
        paymentId: row.sourcePaymentId,
        status: row.rentCertDue ? "due" : "notDue",
      });
    }

    if (before.paidStatus === "projected" && row.paidStatus === "invoice-submitted" && row.sourcePaymentId) {
      spendPosts.push({
        enrollmentId: row.enrollmentId,
        paymentId: row.sourcePaymentId,
        note: row.notes || undefined,
        vendor: row.vendor || undefined,
      });
    }

    if (!isScheduleChanged(before, row)) continue;

    if (before.paid) {
      const edit = toProjectionEdit(row);
      if (!edit) continue;
      paidAdjustments.push({
        enrollmentId: row.enrollmentId,
        spendAdjustment: {
          paymentId: row.sourcePaymentId,
          newAmount: edit.amount,
          dueDate: edit.dueDate,
          lineItemId: edit.lineItemId,
          note: edit.note,
          vendor: edit.vendor,
          reason: "Payment sheet paid-row adjustment",
        },
        options: { updateGrantBudgets: true, recalcGrantProjected: true, activeOnly: true },
      });
    } else {
      const edit = toProjectionEdit(row);
      if (edit) ensureProjection(row.enrollmentId).edits!.push(edit);
    }
  }

  for (const [id, before] of baseline.rows.entries()) {
    if (currentById.has(id)) continue;
    if (before.paid) {
      paidDeletes.push({
        enrollmentId: before.enrollmentId,
        deleteRows: {
          paymentIds: [before.sourcePaymentId],
          preservePaid: false,
          updateBudgets: true,
          removeSpends: true,
          reverseLedger: true,
        },
        options: { updateGrantBudgets: true, recalcGrantProjected: true, activeOnly: true },
      });
    } else if (before.sourcePaymentId) {
      ensureProjection(before.enrollmentId).deleteIds!.push(before.sourcePaymentId);
    }
  }

  if (paidAdjustments.length > 1) {
    validationErrors.push("Only one paid row schedule edit can be saved at a time.");
  }

  const projectionAdjustments: PaymentEditorSavePlan["projectionAdjustments"] = Array.from(projectionByEnrollment.entries())
    .map(([enrollmentId, projectionAdjustment]) => ({ enrollmentId, projectionAdjustment, options: { updateGrantBudgets: true, recalcGrantProjected: true, activeOnly: true } }))
    .filter((item) =>
      (item.projectionAdjustment.edits?.length || 0) > 0 ||
      (item.projectionAdjustment.additions?.length || 0) > 0 ||
      (item.projectionAdjustment.deleteIds?.length || 0) > 0
    );

  return {
    validationErrors,
    compliancePatches,
    spendPosts,
    rentCertPatches,
    projectionAdjustments,
    paidAdjustments,
    paidDeletes,
    changedRowIds,
  };
}

export function summarizePaymentEditorRows(rows: PaymentEditorRow[], selectedIds?: Set<string>) {
  let total = 0;
  let selected = 0;
  let projected = 0;
  let submitted = 0;
  for (const row of rows) {
    const amount = amountNumber(row.amount);
    total += amount;
    if (selectedIds?.has(row.id)) selected += amount;
    if (row.paidStatus === "invoice-submitted") submitted += amount;
    else projected += amount;
  }
  return { total, selected, projected, submitted, rowCount: rows.length };
}
